apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adapter
  name: adapter
spec:
  containers:
  - image: busybox
    name: app
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"$(date) | $(du -sh ~)\" >> /var/logs/diskspace.txt; sleep 5; done;"]
    volumeMounts:
        - mountPath: /var/logs
          name: cache-volume
    resources: {}
  - image: busybox
    name: transformer
    command: ["/bin/sh"]
    args: ["-c", "sleep 20; while true; do while read LINE; do echo \"$LINE\" | cut -f2 -d\"|\" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;"]
    resources: {}
    volumeMounts:
        - mountPath: /var/logs
          name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
