apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx:2.3.5
    name: mypod
    resources:
      requests:
        memory: "64m"
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
