apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  - args:
    - /bin/sh
    - -c
    - wget -O /work-dir/index.html https://kubernetes.io
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - mountPath: /work-dir
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
